### ISSUE TITLE
`wapm publish` does not accept "wasm4" as an ABI

### ISSUE THREAD

**Issue by tau-dev** [wasmerio/wasm4-on-wapm#1]
With the `wapm.toml`:
```toml
[package]
name = "tau-dev/taufl1"
version = "0.1.0"
description = "A flight simulator on WASM-4."
license = "ISC"
readme = "README.md"

[[module]]
name = "taufl1"
source = "zig-out/lib/taufl1.wasm"
abi = "wasm4"
interfaces = { wasm4 = "0.0.1" }

[[command]]
runner = "wasm4@0.0.1"
name = "play"
module = "taufl1"
```
I get an
```
Error: Could not parse manifest because unknown variant `wasm4`, expected one of `emscripten`, `none`, `wasi` for key `module.abi`
```
